import React, { useEffect, useMemo, useState } from 'react';
import { useClerk } from '@clerk/clerk-react';
import { useApp } from '../../context/AppContext';
import { DollarSign, Image, LogOut, MapPin, Pencil, Plus, RefreshCw, Search, ShoppingBag, Store, Trash2, Utensils, X } from 'lucide-react';
import { Order, OrderStatus, Product } from '../../types';

const emptyProduct = (restaurantId = '', restaurantName = '', categoryId = ''): Omit<Product, 'id' | 'createdAt'> => ({ restaurantId, restaurantName, categoryId, nameFR: '', nameEN: '', descriptionFR: '', descriptionEN: '', imageUrl: '', price: 0, originalPrice: undefined, available: true, rating: 4.9, reviewCount: 0, prepTimeMinutes: 20, isSpicy: false, isPopular: false, isSignature: false, ingredientsFR: [], ingredientsEN: [], options: [] });

export const AdminDashboardScreen: React.FC = () => {
  const { signOut } = useClerk();
  const { t, orders, restaurants, bookings, products, categories, updateOrderStatus, showToast, isSupabaseConnected, syncData, addNewProduct, updateProduct, deleteProduct, toggleProductAvailability } = useApp();
  const [liveOrders, setLiveOrders] = useState<Order[]>(orders);
  const [selectedStatusFilter, setSelectedStatusFilter] = useState<string>('all');
  const [isSyncing, setIsSyncing] = useState(false);
  const [productSearch, setProductSearch] = useState('');
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [newProduct, setNewProduct] = useState<Omit<Product, 'id' | 'createdAt'> | null>(null);
  const [savingProduct, setSavingProduct] = useState(false);

  useEffect(() => { setLiveOrders(orders); }, [orders]);

  // Orders are read through the authenticated server endpoint because browser RLS intentionally blocks public order reads.
  // Polling every 3 seconds gives the Admin Control Center a near-real-time feed without exposing all orders to customers.
  useEffect(() => {
    let cancelled = false;
    const loadLiveOrders = async () => {
      try {
        const clerk = (window as typeof window & { Clerk?: { session?: { getToken?: () => Promise<string | null> } } }).Clerk;
        const token = clerk?.session?.getToken ? await clerk.session.getToken() : null;
        if (!token) return;
        const response = await fetch('/api/admin/orders', { headers: { Authorization: `Bearer ${token}` } });
        if (!response.ok) return;
        const result = await response.json().catch(() => ({}));
        if (!cancelled && Array.isArray(result.orders)) setLiveOrders(result.orders);
      } catch (error) { console.warn('Live admin order feed failed:', error); }
    };
    loadLiveOrders();
    const timer = window.setInterval(loadLiveOrders, 3000);
    return () => { cancelled = true; window.clearInterval(timer); };
  }, []);

  const totalRevenue = liveOrders.reduce((sum, o) => sum + (o.total || 0), 0);
  const activeOrdersCount = liveOrders.filter((o) => o.orderStatus !== 'delivered' && o.orderStatus !== 'cancelled').length;
  const visibleOrders = liveOrders.filter((o) => selectedStatusFilter === 'all' || o.orderStatus === selectedStatusFilter);
  const visibleProducts = useMemo(() => products.filter((p) => `${p.nameFR} ${p.nameEN} ${p.restaurantName}`.toLowerCase().includes(productSearch.toLowerCase())), [products, productSearch]);
  const handleManualSync = async () => { setIsSyncing(true); await syncData(); setIsSyncing(false); showToast('Données synchronisées avec Supabase !'); };
  const startNewProduct = () => { const r = restaurants[0]; setEditingProduct(null); setNewProduct(emptyProduct(r?.id || '', r?.name || '', categories[0]?.id || '')); };
  const save = async () => { setSavingProduct(true); try { if (editingProduct) { if (await updateProduct(editingProduct)) { showToast('Produit mis à jour.'); setEditingProduct(null); } else showToast('Échec de mise à jour du produit.'); } else if (newProduct) { await addNewProduct(newProduct); showToast('Produit ajouté.'); setNewProduct(null); } } catch { showToast('Impossible d’enregistrer le produit.'); } finally { setSavingProduct(false); } };
  const confirmDelete = async (id: string) => { if (!window.confirm('Supprimer ce produit définitivement ?')) return; if (await deleteProduct(id)) showToast('Produit supprimé.'); else showToast('Échec de suppression.'); };

  return (
    <div id="admin-dashboard" className="p-4 sm:p-6 pb-28 max-w-7xl mx-auto space-y-6">
      <div className="bg-gradient-to-r from-[#006633] via-[#0A522A] to-[#1F2937] text-white rounded-[32px] p-6 sm:p-8 shadow-artistic-lg flex flex-col sm:flex-row sm:items-center justify-between gap-4 border border-emerald-700/30">
        <div><div className="flex items-center gap-2 mb-1.5 flex-wrap"><span className="px-3 py-1 rounded-full bg-white/15 border border-white/20 text-[#FFCC00] text-xs font-black uppercase tracking-wider">👑 Teranga HQ</span><span className="text-xs text-white/80 font-semibold">Admin Control Center</span></div><h2 className="font-heading font-black text-2xl sm:text-3xl text-white">{t('adminDashboardTitle')}</h2><p className="text-xs sm:text-sm text-white/70 mt-1 font-medium">Supervision en temps réel des commandes et de la base de données</p></div>
        <div className="flex items-center gap-2 flex-wrap"><button onClick={handleManualSync} disabled={isSyncing} className="px-3.5 py-2 rounded-2xl bg-white/20 hover:bg-white/30 text-white text-xs font-black border border-white/30 flex items-center gap-1.5"><RefreshCw className={`w-3.5 h-3.5 ${isSyncing ? 'animate-spin' : ''}`} />Actualiser DB</button><button onClick={() => signOut()} className="px-3.5 py-2 rounded-2xl bg-red-500/20 hover:bg-red-500/30 text-white text-xs font-black border border-red-300/30 flex items-center gap-1.5"><LogOut className="w-3.5 h-3.5" />Déconnexion</button><span className="px-3.5 py-2 rounded-2xl bg-emerald-500/20 text-emerald-300 text-xs font-black border border-emerald-500/30">● {isSupabaseConnected ? 'Supabase Connecté' : 'Base locale'}</span></div>
      </div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-[28px] p-5 border border-[#F0EDE8] shadow-artistic"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-gray-500">{t('adminTotalSales')}</span><DollarSign className="w-4 h-4 text-[#006633]" /></div><p className="font-heading font-black text-xl text-[#2D2D2D]">{totalRevenue.toLocaleString()} FCFA</p><p className="text-[10px] text-[#006633] font-black mt-1">Chiffre d'affaires réel</p></div>
        <div className="bg-white rounded-[28px] p-5 border border-[#F0EDE8] shadow-artistic"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-gray-500">{t('adminTotalOrders')}</span><ShoppingBag className="w-4 h-4 text-amber-700" /></div><p className="font-heading font-black text-xl text-[#2D2D2D]">{liveOrders.length} commandes</p><p className="text-[10px] text-amber-700 font-black mt-1">{activeOrdersCount} en cours</p></div>
        <div className="bg-white rounded-[28px] p-5 border border-[#F0EDE8] shadow-artistic"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-gray-500">{t('adminActiveRestaurants')}</span><Store className="w-4 h-4 text-[#007CB0]" /></div><p className="font-heading font-black text-xl text-[#2D2D2D]">{restaurants.length} partenaires</p><p className="text-[10px] text-sky-700 font-black mt-1">Restaurants actifs</p></div>
        <div className="bg-white rounded-[28px] p-5 border border-[#F0EDE8] shadow-artistic"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-gray-500">Réservations Tables</span><Utensils className="w-4 h-4 text-purple-800" /></div><p className="font-heading font-black text-xl text-[#2D2D2D]">{bookings.length} réservées</p><p className="text-[10px] text-purple-700 font-black mt-1">En direct</p></div>
      </div>
      <section className="bg-white rounded-[32px] p-6 border border-[#F0EDE8] shadow-artistic space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-[#F0EDE8]"><div><h3 className="font-heading font-black text-lg text-[#2D2D2D]">Flux des commandes en direct</h3><p className="text-xs text-gray-500 font-medium">Nouvelles commandes chargées automatiquement toutes les 3 secondes.</p></div><div className="flex gap-1.5 overflow-x-auto no-scrollbar bg-[#F7F5F0] p-1 rounded-2xl">{['all', 'pending', 'preparing', 'delivering', 'delivered'].map((filter) => <button key={filter} onClick={() => setSelectedStatusFilter(filter)} className={`px-3.5 py-1.5 rounded-xl text-xs font-black ${selectedStatusFilter === filter ? 'bg-[#006633] text-white' : 'text-gray-600'}`}>{filter === 'all' ? 'Toutes' : filter}</button>)}</div></div>
        <div className="space-y-3">{visibleOrders.length === 0 ? <div className="text-center py-10 text-gray-400"><ShoppingBag className="w-8 h-8 mx-auto mb-2 opacity-40" /><p className="text-xs font-bold">Aucune commande enregistrée pour ce filtre.</p><p className="text-[11px]">Les nouvelles commandes apparaîtront automatiquement ici.</p></div> : visibleOrders.map((order) => <div key={order.id} className="p-4 sm:p-5 rounded-[24px] border border-[#F0EDE8] bg-[#FAF8F5] flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="space-y-1.5"><div className="flex items-center gap-2"><span className="font-black text-xs text-[#006633]">{order.id}</span><span className="px-2.5 py-0.5 rounded-full bg-emerald-100 text-[#006633] text-[10px] font-black uppercase">{order.orderStatus}</span><span className="text-xs font-black">{order.total.toLocaleString()} FCFA</span></div><p className="text-xs font-bold">{order.customerName} → {order.restaurantName}</p><p className="text-[11px] text-gray-500 flex items-center gap-1"><MapPin className="w-3 h-3 text-[#006633]" />{order.deliveryAddress?.neighborhood} ({order.deliveryAddress?.streetAddress})</p></div><div className="flex items-center gap-1.5 flex-wrap">{(['preparing', 'ready', 'delivering', 'delivered'] as OrderStatus[]).map((st) => <button key={st} onClick={async () => { await updateOrderStatus(order.id, st); showToast(`Statut ${order.id} : ${st}`); }} className={`px-3 py-1.5 rounded-xl text-xs font-black ${order.orderStatus === st ? 'bg-[#006633] text-white' : 'bg-white border border-[#F0EDE8] text-gray-700'}`}>{st}</button>)}</div></div>)}</div>
      </section>
      <section className="bg-white rounded-[32px] p-6 border border-[#F0EDE8] shadow-artistic space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h3 className="font-heading font-black text-lg text-[#2D2D2D]">Gestion des produits</h3><p className="text-xs text-gray-500">Ajoutez, modifiez, masquez ou supprimez les plats affichés aux clients.</p></div><button onClick={startNewProduct} className="px-4 py-2.5 rounded-2xl bg-[#006633] text-white text-xs font-black flex items-center gap-2"><Plus className="w-4 h-4" />Ajouter un produit</button></div>
        <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" /><input value={productSearch} onChange={(e) => setProductSearch(e.target.value)} placeholder="Rechercher un produit…" className="w-full pl-10 pr-4 py-3 rounded-2xl border border-[#E8E3DA] bg-[#FAF8F5] text-sm outline-none focus:border-[#006633]" /></div>
        <div className="grid gap-3">{visibleProducts.map((p) => <div key={p.id} className="rounded-2xl border border-[#F0EDE8] p-3 flex gap-3 items-center"><img src={p.imageUrl || 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=120&q=80'} className="w-16 h-16 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="font-black text-sm truncate">{p.nameFR || p.nameEN}</p><p className="text-[11px] text-gray-500 truncate">{p.nameEN} · {p.restaurantName}</p><p className="text-xs font-black text-[#006633] mt-1">{p.price.toLocaleString()} FCFA</p></div><button onClick={async () => { await toggleProductAvailability(p.id); }} className={`px-2.5 py-1.5 rounded-xl text-[10px] font-black ${p.available ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>{p.available ? 'Disponible' : 'Masqué'}</button><button onClick={() => setEditingProduct({...p})} className="p-2 rounded-xl bg-slate-100 text-slate-700"><Pencil className="w-4 h-4" /></button><button onClick={() => confirmDelete(p.id)} className="p-2 rounded-xl bg-red-50 text-red-600"><Trash2 className="w-4 h-4" /></button></div>)}{visibleProducts.length === 0 && <p className="text-center py-8 text-sm text-gray-400">Aucun produit trouvé.</p>}</div>
      </section>
      {(editingProduct || newProduct) && <div className="fixed inset-0 z-[100] bg-black/50 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-2xl max-h-[92vh] overflow-y-auto bg-white rounded-[28px] p-6 shadow-2xl"><div className="flex items-center justify-between mb-5"><div><h3 className="font-heading font-black text-xl">{editingProduct ? 'Modifier le produit' : 'Ajouter un produit'}</h3><p className="text-xs text-gray-500">Tous les changements sont enregistrés dans Supabase.</p></div><button onClick={() => { setEditingProduct(null); setNewProduct(null); }} className="p-2 rounded-xl bg-gray-100"><X className="w-5 h-5" /></button></div><ProductForm product={editingProduct || newProduct!} categories={categories} restaurants={restaurants} onChange={(p) => editingProduct ? setEditingProduct(p as Product) : setNewProduct(p as Omit<Product, 'id' | 'createdAt'>)} /><div className="flex justify-end gap-2 mt-6"><button onClick={() => { setEditingProduct(null); setNewProduct(null); }} className="px-4 py-2.5 rounded-2xl border text-sm font-bold">Annuler</button><button disabled={savingProduct} onClick={save} className="px-5 py-2.5 rounded-2xl bg-[#006633] text-white text-sm font-black disabled:opacity-50">{savingProduct ? 'Enregistrement…' : 'Enregistrer'}</button></div></div></div>}
    </div>
  );
};

const ProductForm: React.FC<{ product: Product | Omit<Product, 'id' | 'createdAt'>; categories: any[]; restaurants: any[]; onChange: (p: any) => void }> = ({ product, categories, restaurants, onChange }) => {
  const set = (key: string, value: any) => onChange({...product, [key]: value});
  return <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{[['nameFR','Nom français'],['nameEN','Nom anglais'],['descriptionFR','Description française'],['descriptionEN','Description anglaise'],['price','Prix (FCFA)'],['originalPrice','Ancien prix (optionnel)'],['imageUrl','URL image']].map(([key,label]) => <label key={key} className={key.includes('description') || key==='imageUrl' ? 'sm:col-span-2 text-xs font-bold text-gray-700' : 'text-xs font-bold text-gray-700'}>{label}<div className="relative mt-1">{key==='imageUrl' && <Image className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />}<input type={key.includes('price') ? 'number' : 'text'} value={(product as any)[key] ?? ''} onChange={e => set(key, key.includes('price') ? (e.target.value === '' ? undefined : Number(e.target.value)) : e.target.value)} className={`w-full ${key==='imageUrl'?'pl-10':''} px-3 py-2.5 rounded-xl border border-gray-200 text-sm font-medium`} /></div></label>)}<label className="text-xs font-bold text-gray-700">Restaurant<select value={product.restaurantId} onChange={e => { const r=restaurants.find(x=>x.id===e.target.value); onChange({...product,restaurantId:e.target.value,restaurantName:r?.name||product.restaurantName}); }} className="mt-1 w-full px-3 py-2.5 rounded-xl border border-gray-200"><option value="">Sélectionner</option>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="text-xs font-bold text-gray-700">Catégorie<select value={product.categoryId} onChange={e=>set('categoryId',e.target.value)} className="mt-1 w-full px-3 py-2.5 rounded-xl border border-gray-200"><option value="">Sélectionner</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nameFR || c.nameEN}</option>)}</select></label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={product.available} onChange={e=>set('available',e.target.checked)} /> Disponible à la vente</label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!product.isPopular} onChange={e=>set('isPopular',e.target.checked)} /> Populaire</label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!product.isSignature} onChange={e=>set('isSignature',e.target.checked)} /> Signature</label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!product.isSpicy} onChange={e=>set('isSpicy',e.target.checked)} /> Épicé</label></div>;
};
