import React, { useEffect, useRef, useState } from 'react';
import { LogOut, MapPin, Navigation, Package, Phone, Power, ShieldCheck, Truck } from 'lucide-react';
import { Order, OrderStatus } from '../../types';

type Driver = { id:string; fullName:string; phone:string; vehicleType:string; vehiclePlate:string; rating:number; totalDeliveries:number; photoUrl:string; active:boolean };

const statusLabel: Record<string,string> = { assigned:'Assignée', picked_up:'Récupérée', delivering:'En livraison', driver_arrived:'Livreur arrivé', delivered:'Livrée' };

export const DriverScreen: React.FC = () => {
  const [driver,setDriver]=useState<Driver|null>(null); const [orders,setOrders]=useState<Order[]>([]); const [login,setLogin]=useState(''); const [password,setPassword]=useState('');
  const [loading,setLoading]=useState(true); const [logging,setLogging]=useState(false); const [error,setError]=useState(''); const [sharing,setSharing]=useState<string|null>(null); const [coords,setCoords]=useState<GeolocationCoordinates|null>(null); const watchRef=useRef<number|null>(null);

  const loadSession=async()=>{ try { const r=await fetch('/api/driver/session',{credentials:'include'}); const d=await r.json().catch(()=>({})); if(r.ok&&d.driver){setDriver(d.driver);return true;} } catch {} return false; };
  const loadOrders=async()=>{ try { const r=await fetch('/api/driver/orders',{credentials:'include'}); const d=await r.json().catch(()=>({})); if(r.ok&&Array.isArray(d.orders)) setOrders(d.orders); } catch {} };

  useEffect(()=>{ (async()=>{const ok=await loadSession(); if(ok) await loadOrders(); setLoading(false);})(); return ()=>{if(watchRef.current!==null)navigator.geolocation?.clearWatch(watchRef.current);}; },[]);
  useEffect(()=>{if(!driver)return; const timer=window.setInterval(loadOrders,5000); return()=>window.clearInterval(timer);},[driver]);

  const doLogin=async(e:React.FormEvent)=>{e.preventDefault();setLogging(true);setError('');try{const r=await fetch('/api/driver/login',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({login,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Connexion impossible');setDriver(d.driver);setPassword('');await loadOrders();}catch(err){setError(err instanceof Error?err.message:'Connexion impossible.');}finally{setLogging(false);}};
  const logout=async()=>{if(watchRef.current!==null)navigator.geolocation?.clearWatch(watchRef.current);await fetch('/api/driver/logout',{method:'POST',credentials:'include'}).catch(()=>{});setDriver(null);setOrders([]);setSharing(null);};

  const updateStatus=async(orderId:string,status:OrderStatus)=>{const r=await fetch(`/api/driver/orders/${encodeURIComponent(orderId)}/status`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(r.ok)await loadOrders();};
  const startGps=(orderId:string)=>{if(!navigator.geolocation){setError('GPS non disponible sur cet appareil.');return;}if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);setError('');setSharing(orderId);watchRef.current=navigator.geolocation.watchPosition(async p=>{setCoords(p.coords);await fetch('/api/driver/location',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy})}).catch(()=>{});},()=>setError('Autorisez la localisation GPS pour partager votre position.'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});};
  const stopGps=()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;setSharing(null);};

  if(loading)return <div className="min-h-screen bg-[#F7F5F0] flex items-center justify-center text-sm font-black">Chargement Driver…</div>;
  if(!driver)return <div className="min-h-screen bg-[#F7F5F0] flex items-center justify-center p-5"><form onSubmit={doLogin} className="w-full max-w-md bg-white rounded-[32px] p-7 border border-[#F0EDE8] shadow-artistic space-y-5"><div className="w-14 h-14 rounded-2xl bg-[#006633] text-[#FFCC00] flex items-center justify-center"><Truck className="w-7 h-7"/></div><div><h1 className="font-heading font-black text-2xl">TerangaEats Driver</h1><p className="text-xs text-gray-500 mt-1">Connectez-vous pour voir vos commandes assignées.</p></div><div className="p-3 rounded-2xl bg-emerald-50 border border-emerald-200 text-xs text-emerald-900 flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0"/>Votre session est sécurisée par un cookie HttpOnly.</div><label className="block text-xs font-black">ID / Email / Téléphone<input value={login} onChange={e=>setLogin(e.target.value)} required className="mt-1 w-full p-3.5 rounded-2xl bg-[#F7F5F0] outline-none border border-transparent focus:border-[#006633]"/></label><label className="block text-xs font-black">Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required className="mt-1 w-full p-3.5 rounded-2xl bg-[#F7F5F0] outline-none border border-transparent focus:border-[#006633]"/></label>{error&&<p className="text-xs font-bold text-red-600">{error}</p>}<button disabled={logging} className="w-full p-4 rounded-2xl bg-[#006633] text-white font-black disabled:opacity-50">{logging?'Connexion…':'Se connecter'}</button></form></div>;

  return <div className="min-h-screen bg-[#F7F5F0] p-4 sm:p-6 pb-12"><div className="max-w-3xl mx-auto space-y-5"><header className="bg-gradient-to-r from-[#006633] to-[#0A522A] text-white rounded-[30px] p-5 flex items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#FFCC00]">TerangaEats Driver</p><h1 className="font-heading font-black text-2xl">Bonjour, {driver.fullName}</h1><p className="text-xs text-white/70 mt-1">{driver.vehicleType} · {driver.vehiclePlate || 'Plaque non renseignée'} · {driver.totalDeliveries} livraisons</p></div><button onClick={logout} className="p-3 rounded-2xl bg-white/15 border border-white/20"><LogOut className="w-5 h-5"/></button></header>
    {error&&<div className="bg-red-50 text-red-700 border border-red-200 rounded-2xl p-3 text-xs font-bold">{error}</div>}
    <section className="bg-white rounded-[30px] p-5 border border-[#F0EDE8] shadow-artistic"><div className="flex items-center justify-between mb-4"><div><h2 className="font-heading font-black text-lg">Mes commandes</h2><p className="text-xs text-gray-500">Les nouvelles affectations apparaissent automatiquement.</p></div><span className="px-3 py-1.5 rounded-xl bg-emerald-100 text-[#006633] text-xs font-black">{orders.length} assignée(s)</span></div>
      <div className="space-y-4">{orders.length===0?<div className="py-12 text-center text-gray-400"><Package className="w-9 h-9 mx-auto mb-2 opacity-40"/><p className="text-sm font-black">Aucune commande assignée.</p></div>:orders.map(order=><article key={order.id} className="rounded-[25px] border border-[#E9E4DB] bg-[#FAF8F5] p-4 space-y-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 flex-wrap"><b className="text-xs text-[#006633]">{order.id}</b><span className="px-2.5 py-1 rounded-full bg-emerald-100 text-[#006633] text-[10px] font-black uppercase">{statusLabel[order.orderStatus]||order.orderStatus}</span></div><p className="font-black mt-1">{order.customerName}</p><p className="text-xs text-gray-500 flex items-center gap-1"><MapPin className="w-3 h-3"/>{order.deliveryAddress?.neighborhood}, {order.deliveryAddress?.streetAddress}</p></div><a href={`tel:${order.customerPhone}`} className="p-2.5 rounded-xl bg-white border border-[#E9E4DB]"><Phone className="w-4 h-4 text-[#006633]"/></a></div><div className="text-xs text-gray-600 space-y-1"><p><b>Restaurant:</b> {order.restaurantName}</p><p><b>Total:</b> {(order.total||0).toLocaleString()} FCFA</p></div><div className="flex gap-2 flex-wrap">{order.orderStatus==='assigned'&&<button onClick={()=>updateStatus(order.id,'picked_up')} className="px-3 py-2 rounded-xl bg-[#006633] text-white text-xs font-black">J'ai récupéré</button>}{order.orderStatus==='picked_up'&&<button onClick={()=>{updateStatus(order.id,'delivering');startGps(order.id);}} className="px-3 py-2 rounded-xl bg-[#006633] text-white text-xs font-black flex gap-1.5 items-center"><Navigation className="w-4 h-4"/>Démarrer livraison + GPS</button>}{order.orderStatus==='delivering'&&<button onClick={()=>updateStatus(order.id,'driver_arrived')} className="px-3 py-2 rounded-xl bg-amber-600 text-white text-xs font-black">Je suis arrivé</button>}{order.orderStatus==='driver_arrived'&&<button onClick={()=>{updateStatus(order.id,'delivered');if(sharing===order.id)stopGps();}} className="px-3 py-2 rounded-xl bg-[#006633] text-white text-xs font-black">Marquer livrée</button>}{sharing===order.id&&<button onClick={stopGps} className="px-3 py-2 rounded-xl bg-red-600 text-white text-xs font-black flex gap-1.5 items-center"><Power className="w-4 h-4"/>Arrêter GPS</button>}</div>{sharing===order.id&&coords&&<div className="text-[11px] font-bold text-[#006633] bg-emerald-50 rounded-xl p-3">GPS actif · {coords.latitude.toFixed(6)}, {coords.longitude.toFixed(6)} · ±{Math.round(coords.accuracy)}m</div>}</article>)}</div>
    </section></div></div>;
};
