import React, { useEffect, useState } from 'react';
import { KeyRound, UserPlus, Truck } from 'lucide-react';
import { Order } from '../../types';

type Driver={id:string;fullName:string;phone:string;vehicleType:string;vehiclePlate:string;active:boolean;totalDeliveries:number};
export const DriverAssignmentPanel:React.FC<{orders:Order[]}>=({orders})=>{
 const [drivers,setDrivers]=useState<Driver[]>([]); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState({id:'',fullName:'',phone:'',email:'',password:'',vehicleType:'Moto',vehiclePlate:''}); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
 const load=async()=>{const r=await fetch('/api/admin/drivers',{credentials:'include'});const d=await r.json().catch(()=>({}));if(r.ok)setDrivers(d.drivers||[]);};
 useEffect(()=>{void load();},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy('create');setMessage('');const r=await fetch('/api/admin/drivers',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(r.ok){setMessage('Driver créé.');setForm({id:'',fullName:'',phone:'',email:'',password:'',vehicleType:'Moto',vehiclePlate:''});setShowForm(false);await load();}else setMessage(d.error||'Création impossible.');setBusy('');};
 const assign=async(orderId:string,driverId:string)=>{if(!driverId)return;setBusy(orderId);const r=await fetch(`/api/admin/orders/${encodeURIComponent(orderId)}/assign-driver`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({driverId})});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Livreur assigné.':(d.error||'Assignation impossible.'));setBusy('');};
 return <section className="bg-white rounded-[32px] p-5 sm:p-6 border border-[#F0EDE8] shadow-artistic space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h3 className="font-heading font-black text-lg">Livreurs & affectation</h3><p className="text-xs text-gray-500">Créez les comptes Driver puis affectez chaque commande.</p></div><button onClick={()=>setShowForm(v=>!v)} className="px-4 py-2.5 rounded-2xl bg-[#006633] text-white text-xs font-black flex items-center gap-2"><UserPlus className="w-4 h-4"/>{showForm?'Fermer':'Nouveau Driver'}</button></div>
 {showForm&&<form onSubmit={create} className="grid sm:grid-cols-2 gap-3 p-4 rounded-2xl bg-[#FAF8F5] border border-[#E9E4DB]"><Input label="Driver ID" value={form.id} onChange={v=>setForm({...form,id:v})} required/><Input label="Nom complet" value={form.fullName} onChange={v=>setForm({...form,fullName:v})} required/><Input label="Téléphone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Input label="Email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Input label="Mot de passe (6+)" type="password" value={form.password} onChange={v=>setForm({...form,password:v})} required/><Input label="Type véhicule" value={form.vehicleType} onChange={v=>setForm({...form,vehicleType:v})}/><Input label="Plaque" value={form.vehiclePlate} onChange={v=>setForm({...form,vehiclePlate:v})}/><div className="sm:col-span-2"><button disabled={busy==='create'} className="px-4 py-2.5 rounded-xl bg-[#006633] text-white text-xs font-black disabled:opacity-50"><KeyRound className="w-3.5 h-3.5 inline mr-1"/>Créer le compte</button></div></form>}
 {message&&<p className="text-xs font-black text-[#006633]">{message}</p>}
 <div className="grid gap-3">{orders.filter(o=>!['delivered','cancelled'].includes(o.orderStatus)).map(o=><div key={o.id} className="p-4 rounded-2xl border border-[#F0EDE8] bg-[#FAF8F5] flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="text-xs font-black text-[#006633]">{o.id} · {o.orderStatus}</p><p className="text-sm font-black">{o.customerName}</p><p className="text-[11px] text-gray-500"><Truck className="w-3 h-3 inline mr-1"/>{o.driver?.name||'Aucun livreur'}</p></div><select disabled={busy===o.id} value={o.driver?.id||''} onChange={e=>assign(o.id,e.target.value)} className="w-full sm:w-64 rounded-xl border border-[#E5E0D8] p-3 bg-white text-xs font-bold"><option value="">Choisir un livreur…</option>{drivers.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.fullName} · {d.vehicleType}</option>)}</select></div>)}{orders.filter(o=>!['delivered','cancelled'].includes(o.orderStatus)).length===0&&<p className="text-sm text-gray-400 text-center py-6">Aucune commande active.</p>}</div>
 </section>;
};
const Input:React.FC<{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}>=({label,value,onChange,type='text',required})=><label className="text-xs font-black">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-[#E5E0D8] p-3 outline-none focus:border-[#006633]"/></label>;
